name: Deploy - Staging
on:
  push:
    branches:
      - "main"
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ELEVENTY_ENV: stage
      DATA_DOMAIN: stage
      TRACKING_SCRIPT_LOC: https://cdn.jsdelivr.net/npm/@datacite/datacite-tracker
      TRACKING_API_ENDPOINT: https://analytics.stage.datacite.org/
      DASHBOARD_URL: https://analytics.stage.datacite.org/demorepo.stage.datacite.org
      DASHBOARD_URL_FABRICA: https://doi.stage.datacite.org/repositories/datacite.demo/analytics
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run build and test
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v2
        with:
          folder: _site
          bucket: ${{ secrets.STAGE_S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true