name: Deploy - Staging
on:
  push:
    branches:
      - "stage"
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RACK_ENV: stage
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Build"

      - name: Deploy
        uses: reggionick/s3-deploy@v2
        with:
          folder: www
          bucket: ${{ secrets.STAGE_S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true